version: '3'

tasks:
  fix:
    cmds:
      - golangci-lint run --fix --color=always 
    desc: Automatically fix linting issues

  lint:
    cmds:
      - golangci-lint run --color=always
    desc: Run golangci-lint on the codebase

  test:
    cmds:
      - go test --count=1 -v -coverprofile cover.out ./...
      - go tool cover -html cover.out -o cover.html
      - go tool cover -func cover.out
      - rm cover.out
    desc: Run unit tests with coverage
    ignore_error: true

  test-1000:
    cmds:
      - go test --count=1000 -failfast ./...
    desc: Run unit tests 1000 times to catch flakiness

  test-pg:
    cmds: 
      - go test --count=1 -v -tags=integration ./tests/postgres/...
    desc: Run database integration tests

  vuln:
    cmds:
      - govulncheck -show=color -test ./...
    desc: Run Go vulnerability checker
    